name: Build app files

on:
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Ensure Gradle Wrapper is Executable
        run: chmod +x gradlew

      - name: Build Exe App
        run: ./gradlew :app:packageExe

      - name: Upload Exe Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Exe
          path: app/build/compose/binaries/main/exe/**/*
          if-no-files-found: error